/*
 * This source file was generated by the Gradle 'init' task
 */
package inss;

import java.io.IOException;
import java.net.URISyntaxException;

public class App {
    public static void main(String[] args) {
        Contribuinte contribuinte;
        try {
            contribuinte = GeradorContribuintes.gerarContribuinte();
            System.out.println(contribuinte);
            System.out.println("O contribuinte irá se aposentar daqui: " + contribuinte.calcularTempoRestanteAposentadoria() + " anos.");
            System.out.println("O salário de aposentadoria será: " + contribuinte.calcularValorAposentadoria());
            //System.out.println("O contribuinte irá se aposentar com: " + contribuinte.calcularIdadeAposentadoria() + " anos.");
        } catch (IOException | URISyntaxException e) {
            System.err.println("An error occurred: " + e.getMessage());
        }
        
    }
}
